import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rob Royson</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex justify-center pt-16'>
        <h1 className='text-2xl'>Welcome</h1>
      </main>
    </div>
  )
}
